//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNVCMS.Data.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDescriptionDisplay { get; set; }
        public string AvataImageUrl { get; set; }
        public Nullable<bool> IsAvataDisplay { get; set; }
        public Nullable<bool> IsHotNews { get; set; }
        public string ContentNews { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> UnPublishDate { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> NewsCategoryID { get; set; }
        public Nullable<int> NewsEventID { get; set; }
    
        public virtual T_NewsCategory T_NewsCategory { get; set; }
        public virtual T_NewsEvents T_NewsEvents { get; set; }
    }
}
