//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNVCMS.Data.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TNVCMS.Data.DataAcess;

    public partial class TNVCMSEntities : DbContext, IDbContext
    {
        public TNVCMSEntities()
            : base("name=TNVCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public new IDbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            return base.Set<TEntity>();
        }
    
        public virtual DbSet<T_News> T_News { get; set; }
        public virtual DbSet<T_NewsCategory> T_NewsCategory { get; set; }
        public virtual DbSet<T_NewsEvents> T_NewsEvents { get; set; }
    }
}
